### ISSUE TITLE
PR review process 

### ISSUE THREAD

**Issue by davinci26** [ysugimoto/falco#104]
@ysugimoto can we get:
* https://github.com/ysugimoto/falco/pull/102
* https://github.com/ysugimoto/falco/pull/90 
* https://github.com/ysugimoto/falco/pull/85

On track to be approved or merged? These PRs have been getting stale and we would like to get them merged.

We want to keep the upstream project and our internal forks as close as possible so taking changes that contain big refactors and/or API changes might hinder our ability in the future to contribute patches.

cc @shadialtarsha

**Comment by ysugimoto** [comment]
@davinci26 sorry for being late, yes let's merge and release them.
I aggregate candidates at #105 so could you check it?

**Comment by davinci26** [comment]
thanks for the support
