### ISSUE TITLE
[Question] Recursive lint

### ISSUE THREAD

**Issue by kevin-fagan** [ysugimoto/falco#111]
Is there a way to recursively lint all VCL files that belong to some repository, or directory? In my case, we don't care to lint the `main.vcl` file, as it does not exist. 

At my company, we package VCL files into a `VCL Package` that is managed by a CI/CD plugin that I wrote. This plugin manages these VCL Packages. It is similar to NPM or pip. Because of this, these VCL Packages do not contain a `main.vcl` file, rather they contain multiple VCL files that get managed by said plugin. My goal here is to use Falco to lint these VCL packages. I have tried passing multiple files to the `I` flag, but that does not seem to work.

**Comment by ysugimoto** [comment]
@kevin-fagan Thanks for reaching out to our project.

Fastly wants entry point VCL file (e.g `main: true` in Fastly console), so the plugin package will be resolved via `include` statement.
However, `falco` could lint for independent VCL file like [example file](https://github.com/ysugimoto/falco/blob/main/examples/default01.vcl). 

Or, just one solving way is that generate an entry point file that contains `include` statement for your package files dynamically:

```vcl
// main.vcl
include "package01/xxx.vcl";
include "package02/yyy.vcl";
include "package03/zzz.vcl";
...
```

And then run `falco ./main.vcl`.

Probably I'm misunderstanding your thought so could you show me more detail with some examples?

**Comment by kevin-fagan** [comment]
No problem! I find this project to be very interesting! Let me try to clarify what I am trying to accomplish. If I have the following files that are apart of a `VCL Package` called `exmaple_package`:

```
vcl_file_1.vcl
vcl_file_2.vcl
vcl_file_3.vcl
```

I would like to lint these files BEFORE they get included into `main.vcl`. I am wondering if this is possible?  I have attempted the following: `falco -I . ./vcl_file_1.vcl ./vcl_file_2.vcl ./vcl_file_3.vcl`

### Backround

The reason I would like to lint these files BEFORE they get included into the `main.vcl` file is because we have created what we call `VCL Packages`. These are packages written in VCL that can be automatically installed into a consumers Fastly service by specifying what VCL package they would like to consume. This is done by specifying the packages you want in a config file that gets read in by the CI/CD plugin that I wrote. This is part of our CI/CD pipeline. 

For example, we may have a config that looks something like this:

```YAML
packages:
    - source: github.com/path/to/exmaple_package/1
    - source: github.com/path/to/exmaple_package/2
    - source: github.com/path/to/exmaple_package/3
```
    
As part of our CI/CD pipeline, before we deploy to Fastly via Terraform, these packages will automatically be installed into the consumers Fastly Service via the plugin I mentioned earlier. The only thing the consumers need to do is specify which packages they would like to consume. And so, it would be useful to lint these packages BEFORE consumers use them.

**Comment by davinci26** [comment]
We are running a similar setup so I have vested interest here but I don't have a good solution:

* can all `vcl_file_*.vcl` be compiled independently? i.e. does `vcl_file_1` define req.http.foo and then  `vcl_file_2` uses req.http.foo?
* if the answer is yes then the problem is that for VCL include order matters so falco would need to know how these files are included to be parsed.

Can you create a "dummy" `main.vcl` as part of your CI script and have it be just include:
```
include "vcl_file_1.vcl"
include "vcl_file_2.vcl"
include "vcl_file_3.vcl"
```

FYI you might want to look into running a similar setup with TF and packaging modules as TF modules. [link](https://registry.terraform.io/providers/fastly/fastly/latest/docs)

**Comment by kevin-fagan** [comment]
@davinci26 Unfortunately, Terraform modules do not solve our use case. But yeah, I think creating a "dummy" `main.vcl` might be the best option. Thanks for your input!
