### ISSUE TITLE
[Feature] Product Icon

### ISSUE THREAD

**Issue by ysugimoto** [ysugimoto/falco#124]
**Describe the feature you'd like**
We want to have a product identity icon 😃 

**Additional context**
I don't have entire skills for design, help wanted!

**Comment by chenrui333** [comment]
You can try [DALL·E 2](https://openai.com/product/dall-e-2) to help create some product log, this is what I found the best generated one:

![falco-logo](https://user-images.githubusercontent.com/1580956/222997944-17cef2aa-c1bf-4e4c-b547-571d016bc38d.png)
