### ISSUE TITLE
[BUG] Terraform Resolver Module's Look up is Failing

### ISSUE THREAD

**Issue by shadialtarsha** [ysugimoto/falco#147]
**Describe the problem**
The Terraform Resolver is not able to look up the modules correctly.

**VCL code that causes the problem**
We are trimming the extension [here](https://github.com/ysugimoto/falco/blob/6fcd3db06970550b53eeccb1d6aaf12668d7b747/resolver/terraform.go#L52) and then we try to look up the module name. However, the modules' names have the `vcl` extension.
Removing this line will fix the issue!

I will issue a PR but I just want to check if I am missing something here!

**Comment by ysugimoto** [comment]
Resolver seems fine even if we don't trim the extension I think.
I look forward to seeing your PR!

**Comment by ysugimoto** [comment]
fixed on https://github.com/ysugimoto/falco/pull/148
