### ISSUE TITLE
[BUG] Parser/Linter error `return;` in `vcl_recv`

### ISSUE THREAD

**Issue by davinci26** [ysugimoto/falco#152]
**Describe the problem**

False positive linter

```
sub vcl_recv {
   return;
}
```

Falco allows it but [fastly doesnt](https://fiddle.fastly.dev/fiddle/5c934b7c)

**Comment by ysugimoto** [comment]
Thanks, I reproduced it on the actual Fastly service and it raises an error.

<img width="1395" alt="Screen Shot 2023-06-15 at 16 40 11" src="https://github.com/ysugimoto/falco/assets/1000401/26b5a5b2-ad7b-462a-a26a-1ea59de0a7c8">

Should be fixed by adding the rule of `disallow empty return`
