### ISSUE TITLE
[BUG] block syntax not being parsed properly

### ISSUE THREAD

**Issue by smaeda-ks** [ysugimoto/falco#17]
**Describe the problem**

The example VCL code below reports this error:

```
💥  Unexpected token "log" found
in /Users/smaeda/Documents/GitHub/falco/foo.vcl at line 3, position 5
 1|sub foo {
 2|  {
 3|    log
       ^^^
```

https://developer.fastly.com/reference/vcl/variables/#user-defined-variables

> Fastly VCL does not provide block scope: declarations apply to an entire subroutine's scope even if a variable is declared within a block.

Fastly does not provide block "scope", but block "syntax" is actually supported even if it has no effect in variable scopes.

**VCL code that cause the problem**

```
sub foo {
  {
    log "hello";
  }
}
```

**Expected behavior**

Should not report errors.

**Comment by ysugimoto** [comment]
This issue should be fixed in https://github.com/ysugimoto/falco/pull/18
