### ISSUE TITLE
[Feature] Support Backdoor to override `req.Host` header in each testing scenario

### ISSUE THREAD

**Issue by Shinyaigeek** [ysugimoto/falco#187]
**Describe the feature you'd like**

In the current implementation, `fastly_info.host_header` will be only `localhost` in the testing because `fastly_info.host_header` is equal to [`req.Host`](https://github.com/ysugimoto/falco/blob/develop/interpreter/variable/all.go#L109) (not, `req.http.Host` which can be overwriten with testing VCL ) and tester send testing request to [`localhost`](https://github.com/ysugimoto/falco/blob/develop/interpreter/variable/all.go#L109).

However, in the real environment, fastly service can have multiple domains, so `fastly_info.host_header` can be multiple value.

I want to test the VCL which configures the behavior according to `fastly_info.host_header`, but I cannot.

I want to the feature to override `req.Host` header in each testing scenario.

**Put example VCL after the feature has been implemented**

This is not related to VCL, but I put the one proposal which I cane up with.

1. Enable `.falco.yaml` configuration file to override `req.Host` header like below

```
testing:
  host: example.com
```

2. Enable each testing scenario VCL to override root config value like below

```
@scope recv
@suite testing some
@config testing.host: example.com,~~
sub test_vcl_hoge {
  // write testing
  assert.equal(fastly_info.host_header, "example.com");
}
```

**Comment by ysugimoto** [comment]
@Shinyaigeek That's a good point, we have some guarantees to enable overriding `req.Host`.

Additionally, the `fastly_info.host_header` indicates the **original** host name which comes from the client request, not overridden one.  I also will fix it.

**Comment by ysugimoto** [comment]
You can see changesets at https://github.com/ysugimoto/falco/pull/189, I will close this issue.

**Comment by Shinyaigeek** [comment]
Sorry for late response, and `rc4` works fine. Thank you!!
