### ISSUE TITLE
[Feature] (testing) Support table definition in unit-tests

### ISSUE THREAD

**Issue by arayaryoma** [ysugimoto/falco#199]
**Describe the feature you'd like**
`falco test` doesn't load table definitions wrttien in test files now, thus we cannnot test vcl depends on the tables.
As current behavior, `falco test` treats this as `Undefined variable {table_name}` error.

**Put example VCL after the feature has been implemented**

`default.vcl`
```vcl
sub vcl_recv {
  set req.http.foo-bar-value = table.lookup(foobar, "value");
}
```

`default.test.vcl`
```vcl

// This table would be loaded by testing interpreter
table foobar {
  "value": "sample",
}

// @scope: recv

sub test_recv {
  testing.call_subroutine("vcl_recv");

  assert.equal(req.http.foo-bar-value, "sample");
}
```

**Additional context**

**Comment by ysugimoto** [comment]
@arayaryoma Thanks for reporting this issue.

The interpreter runs with the provided VCL ( `default.vcl` ), and then injects and runs statements defined in the testing subroutine. This means that any declarations in test files are ignored on testing runtime, and only enable subroutines like `sub test_recv`.

Therefore, in this case, the `foobar` table should be defined at `default.vcl`.
However, your suggestion might be useful for further testing so could you tell me why some tables (or declarations) could be defined in testing VCL?

**Comment by richardmarshall** [comment]
I have a similar situation of having tables (by way of dictionaries), backends, and ACLs defined outside of the VCL. While these are able to be fetched with the `-r` flag from the Fastly API I wanted a way to not require that. 

The solution I went with is a structure like this:
`default.vcl`
```
include "falco";

sub vcl_recv {
  set req.http.foo-bar-value = table.lookup(foobar, "value");
}
```

`falco.vcl`
```
# empty
```

`test/falco.vcl`
```
# this file is only used for tests

table foobar {
  "value": "sample",
}
```

`default.test.vcl`
```
sub test_recv {
  testing.call_subroutine("vcl_recv");

  assert.equal(req.http.foo-bar-value, "sample");
}
```

Using the `-I` flag the `test/falco.vcl` takes precedence over the empty one and the table is available for the test.
```
falco test -I test default.vcl
```

I do think it would be nice for the test code to have a way to set the value of a table key for the execution of the test. Would simplify testing behavior that changes based on the contents of table keys. I can work around that lack of functionality by just having various versions of the `falco.vcl` file with different values set for the table but it would be more convenient if there was a way to do something like `testing.table_set(foobar, "value", "sample");`. Happy to implement such a feature if that seems reasonable to you @ysugimoto.

**Comment by evdokimovn** [comment]
Another use case for this feature is [private dictionaries](https://docs.fastly.com/en/guides/working-with-dictionaries-using-the-web-interface#private-dictionaries) 

Items for such dictionaries are managed outside of Terraform/VCL and cannot be retrieved via API. These usually take a from of private keys or access tokens used in cryptographic operations, the type of operations that are most cumbersome to test. Having a way to set those values in tests/simulations would be highly appreciated.

**Comment by richardmarshall** [comment]
@evdokimovn Private dictionaries are exposed in VCL as string tables like standard dictionaries so code that uses them should be testable/simulated using the same approach as I described above. But I agree that something which doesn't require the empty include hack would be nice.

**Comment by ysugimoto** [comment]
Understood. It could be reasonable for the testing.
Then I can imagine a way of implementation:

```vcl
sub test_recv {
  testing.table_set(foobar, "value", "sample");
}
```

Suggested by @richardmarshall I think this is a good way to inject/override table key-value on testing against existing table.

```vcl
table test_data_for_test {
  "foo": "bar",
}

sub test_recv {
  testing.table_merge(foobar, test_data_for_test);
}
```

This is more useful utility function that merge all table data entirely.

What do you think about it or any other ideas?
