### ISSUE TITLE
[BUG] common subroutine cannot be called from subroutines having different scopes

### ISSUE THREAD

**Issue by lobre** [ysugimoto/falco#240]
Please fill all **required** sections

### Kind of proposals

- []Parser
- [x]Linter
- []Simulator
- []Testing

### Describe the problem

It is not possible to `include`/`call` a same custom subroutine from two subroutines having a different scope. This is because falco always defines a scope for a parsed subroutine. But I am not sure it is supposed to be the case in Fastly.

### VCL code that cause the problem / reproduceable

Let's say I have:

```
$ cat common.vcl

sub mytest BOOL {
  return true;
}
```

And another "main" vcl file:

```
$ cat main.vcl

include "common";

sub vcl_recv {
    declare local var.myvar BOOL;
    set var.myvar = mytest();
}

sub vcl_deliver {
    declare local var.myvar BOOL;
    set var.myvar = mytest();
}
```

And so when I lint my `main.vcl` file, I receive the following error.

```
[ERROR] Function "mytest" is not available in scope DELIVER\nSee reference documentation
```

https://fiddle.fastly.dev/fiddle/f5243e1d

### Expected behavior

The above works in Fastly and does not raise errors.

I see that the reason is that falco always assigns a scope to a subroutine. So if it cannot recognize the scope from a suffix or an annotation, it will assign a recv by default.

https://github.com/ysugimoto/falco/blob/c3ea5168b4f2cff0c4388b09954dd7ec6c378c76/linter/helper.go#L369

In Fastly, there is this "init" scope which seems to be more of an "unscoped" value and will support having subroutines callable from anywhere.

If I relate to the Fastly documentation:

https://developer.fastly.com/reference/vcl/subroutines/

This special mention on that page implies that subroutines are callable from any scope while it uses compatible objects.

> IMPORTANT: The validity of a subroutine to the compiler depends on where it is called from. A subroutine called from [vcl_recv](https://developer.fastly.com/reference/vcl/subroutines/recv/) may contain only code that would be valid within the [vcl_recv](https://developer.fastly.com/reference/vcl/subroutines/recv/) subroutine.

### Desktop (please complete the following information)

**required**
 - OS: Ubuntu 22.04
 - Shell bash

Thanks a lot for your help, and congrats on this great work that helps a lot when working with Fastly locally.

**Comment by ysugimoto** [comment]
Hi @lobre , thank you for reaching out to our project 👋 

It seems to be documented about user subroutine scope recognition here: https://github.com/ysugimoto/falco/blob/main/docs/linter.md#user-defined-subroutine
So you can put an annotation onto your custom subroutine like:

```
$ cat common.vcl

# @scope: recv,deliver
sub mytest BOOL {
  return true;
}
```

Then falco could recognize custom subroutine scope as you want 👍
