### ISSUE TITLE
[BUG] cannot return INTEGER from within an if branch in a subroutine

### ISSUE THREAD

**Issue by lobre** [ysugimoto/falco#241]
Please fill all **required** sections

### Kind of proposals

- []Parser
- []Linter
- [x]Simulator
- []Testing

### Describe the problem

It seems to be kind of a specific bug, but I cannot have a "return" statement within an "if" branch of a subroutine that returns an INTEGER. This is hard to understand with words, so please have a look at the following simple code that better illustrates what I mean.

### VCL code that cause the problem / reproduceable

```
$ cat main.vcl

sub compute INTEGER {
  // pb seems to be around here
  if (true) {
    return 2;
  }
  return 3;
}

sub vcl_recv {
  declare local var.myint INTEGER;
  set var.myint = compute();
}
```

And when I launch the simulator and refresh my browser at http://localhost:3124, I have this error:

```
$ falco simulate main.recv
...
Failed to assign value to var.myint, Invalid assignment for INTEGER type, got NULL
```

Here is a version working in Fastly Fiddle.

https://fiddle.fastly.dev/fiddle/d4bd0467

Also, if I remove the `if` in `compute`, it works:

```
sub compute INTEGER {
  return 2;
}

sub vcl_recv {
  declare local var.myint INTEGER;
  set var.myint = compute();
}
```

### Expected behavior

The above should not raise an error.

### Desktop (please complete the following information)

 - OS: ubuntu 22
 - Shell: bash

**Comment by ysugimoto** [comment]
Hi @lobre , this issue could be reproduced and will be fixed in #242 .
