### ISSUE TITLE
[Feature] Support percent escapes in string literals

### ISSUE THREAD

**Issue by Zifius** [ysugimoto/falco#246]
### Kind of proposals

You can turn on multiple checkboxes.

- Parser
- [x] Linter
- Simulator
- Testing

### Describe the feature

Yesterday I had an issue with broken VCL, when upon upload Fastly was spitting following error:
`Unexpected byte 0xAD in UTF-8 in _short-string_`

I spent quite a bit of time to figure that "%" symbols in a string literal are not allowed and the linter didn't detect this

**required**
Please write solve problem when the feature is added

_Put example VCL after the feature has been implemented_

`if (req.url.path ~ "%test%")`
should output an error 

### Give us your considerations
Here is the docs page which help me to figure where I was wrong:
https://developer.fastly.com/reference/vcl/regex/

**Comment by richardmarshall** [comment]
Haven't had time to work on implementing this but I have identified a few things that need to be considered beyond what is explained in the documentation.

* The surrogate code point range is not valid in either %u or %u{} escapes (0xD800 through 0xDFFF)
* %XX escapes should be considered utf-8 encoded values of between 1 and 4 sequential bytes. With all the utf-8 encoding rules applied.

Not specifically related to % escapes but relevant given the current implementation in falco. The percentage values for the director `.quorum` field are not treated by fastly as a string. We are currently treating them as special case string values which is resulting in cases that are accepted by fastly but not our parser.

For example:
`.quorum = 50 %; // white space between the 50 and the % is accepted`
`.quorum = 50 /* infix comment */ %; // a comment between the 50 and the % is accepted`

Fastly is considering this field an integer expression with the % being a postfix operator:
![Screenshot 2024-01-29 22 30 20](https://github.com/ysugimoto/falco/assets/25832/9fc9f069-64c1-4a4e-8512-a7af0fd4e950)
