### ISSUE TITLE
[BUG] Unexpected token "callback" found

### ISSUE THREAD

**Issue by chenrui333** [ysugimoto/falco#31]
**Describe the problem**
Run into some unexpected token issue when linting the VCL code.

**VCL code that cause the problem**

```
# uses fastly's map function to filter cookies
callback filter_cookies {
  ...
}
```

**Screenshots**
```
$ falco -I service/vcl/ -vv service/main.vcl
💥  Unexpected token "callback" found
in /Users/ruichen/mup/production-fastly-vcl/service/main.vcl at line 1692, position 1
 1687|
 1688|  return(lookup);
 1689|}
 1690|
 1691|# uses fastly's map function to filter cookies sent by the backend for logged in users
 1692|callback filter_cookies
      ^^^^^^^^
```

**Expected behavior**
Passing the linting

**Desktop (please complete the following information):**
 - OS: macOS
 - Shell: bash

**Additional context**

**Comment by xordspar0** [comment]
I'm not familiar with the callback keyword. Is there documentation for it?

**Comment by ysugimoto** [comment]
I couldn't find any documentation on [developer.fastly.com](https://developer.fastly.com/reference/vcl/), too.
However, the `callback` keyword seems to be valid in fastly ([fiddle](https://fiddle.fastlydemo.net/fiddle/6777b419))

@smaeda-ks Do you know about this spec?

**Comment by smaeda-ks** [comment]
No.

We do not allow customers to use `callback` unless they’re approved. I can not share any details.

**Comment by smaeda-ks** [comment]
@ysugimoto We can talk about this offline.
