### ISSUE TITLE
[BUG] testing fails when variables injected by testing.inject_variable are used in a left-hand side of an if statement

### ISSUE THREAD

**Issue by kazukitaninaka** [ysugimoto/falco#350]
Please fill all **required** sections

### Kind of proposals

**required**
You can turn on multiple checkboxes.

- [ ] Parser
- [ ] Linter
- [ ] Simulator
- [x] Testing

### Describe the problem

(Thanks for such a great VCL tool!)

testing fails when variables injected by `testing.inject_variable` are used in a left-hand side of an if statement.
 As far as I understand the code base, the value would always be a literal, meaning `v.isLiteral() = true`, when it is injected by `testing.inject_variable`. Therefore, running test throws an error at this point of code below(L15-19) before the code actually gets evaluated afterwards.

https://github.com/ysugimoto/falco/blob/fd3ffe0d895d362836fed85c9ecabe4997018c0e/interpreter/operator/operator.go#L14-L19

### VCL code that cause the problem / reproduceable

```vcl
# foo.vcl
sub vcl_recv {
  if (client.geo.country_code == "JP") {
    return (pass);
  }
  return (lookup);
}

# foo.test.vcl
// @scope: recv
// @suite: foo
sub test_vcl_recv {
  testing.inject_variable("client.geo.country_code", "JP");
  testing.call_subroutine("vcl_recv");
  assert.state(pass);
}
```

### Expected behavior

testing should not throw an error, meaning it should not go into the if statement below.

https://github.com/ysugimoto/falco/blob/fd3ffe0d895d362836fed85c9ecabe4997018c0e/interpreter/operator/operator.go#L14-L19

### Screenshots

<img width="1360" alt="スクリーンショット 2024-09-24 午前12 50 43" src="https://github.com/user-attachments/assets/0108feb4-d2c0-4466-a8ca-975c9bcc2935">

**Comment by ysugimoto** [comment]
@kazukitaninaka
Thanks for reporting this issue. I reproduced this problem and will fix this!
