### ISSUE TITLE
[BUG] Concatenating TIME to STRING lints as ERROR despite being valid

### ISSUE THREAD

**Issue by Bio2hazard** [ysugimoto/falco#360]
Please fill all **required** sections

### Kind of proposals

**required**
You can turn on multiple checkboxes.

- [] Parser
- [x] Linter
- [] Simulator
- [] Testing

### Describe the problem

When we set cookies with an expiration time, we concatenate TIME to the STRING. This works fine in fastly, but the falco linter flags it with `ERROR` level severity.

Wrapping the time in parentheses resolves the falco error, but actually fails on fastly's side.

No parentheses:    Falco ❌ | Fastly ✔️ 
With parentheses: Falco ✔️ | Fastly ❌ 

### VCL code that cause the problem / reproduceable

`add resp.http.Set-Cookie = "test=abc; domain=fiddle.fastly.dev; path=/; expires=" + now + 5m + ";";`

Falco lints it with:
```
🔥 [ERROR] Expression has TIME type, expected STRING or INTEGER or FLOAT or RTIME or BOOL
in example.vcl at line 10, position 123
 10|  add resp.http.Set-Cookie = "test=abc; domain=fiddle.fastly.dev; path=/; expires=" + now + 5m + ";";
```

But on fastly, this works without any problems.

To try and make falco happy, I added parentheses, like so:
`add resp.http.Set-Cookie = "test=abc; domain=fiddle.fastly.dev; path=/; expires=" + (now + 5m) + ";";`

This removes the falco error, but fastly rejects it with:
```
              │ Error: invalid configuration for Fastly Service (xxx): Warning: Encountered `+` after string expression.
              │ Suggested: Remove the trailing `+` operator.
              │ at: (input Line 123 Pos 123)
              │   add resp.http.Set-Cookie = "test=abc; domain=fiddle.fastly.dev; path=/; expires=" + (now + 5m) + ";";
              │ ------------------------------------------------------------------------------------#------------------
              │ 
              │ Syntax error: Expected variable, string or semicolon, got `(`
              │ at: (input Line 123 Pos 127)
              │   add resp.http.Set-Cookie = "test=abc; domain=fiddle.fastly.dev; path=/; expires=" + (now + 5m) + ";";
              │ --------------------------------------------------------------------------------------#----------------
```

[Fastly Fiddle](https://fiddle.fastly.dev/fiddle/074b7b00) that shows these behaviors.

### Expected behavior

Falco _should not_ throw an error when concatenating STRING with TIME.
Falco _should_ throw an error when concatenating something wrapped in parenthesis.

### Desktop (please complete the following information)

**required**
 - OS: Linux
 - Shell: bash

**Comment by ysugimoto** [comment]
I will look into its behavior and fix it, thanks.
