### ISSUE TITLE
[Feature] Please add support for the bereq.max_reuse_idle_time variable

### ISSUE THREAD

**Issue by Bio2hazard** [ysugimoto/falco#361]
### Kind of proposals

You can turn on multiple checkboxes.

- [x] Parser
- [x] Linter
- [x] Simulator
- [x] Testing

### Describe the feature

Varnish has an undocumented variable `bereq.max_reuse_idle_time`, which can be used in `vcl_miss` and `vcl_pass` to programmatically set the keep-alive time for the TCP session to the backend. It is used when no value for `keepalive_time` is set on the backend definition.

Fiddle: [Fiddle Link](https://fiddle.fastly.dev/fiddle/9fb56bbe)

Unfortunately, falco does not currently know about this variable, so the linter keeps flagging it as an error.

Also, not sure if it is a bug or not, but none of the ignore methods appear to work:
```
    // falco-ignore-start
    // falco-ignore-next-line
    set bereq.max_reuse_idle_time = 3570s; // falco-ignore
    // falco-ignore-end
```

Results in:
```
🔥 [ERROR] Undefined variable "bereq.max_reuse_idle_time"
in file.vcl at line 91, position 9
 90|    // falco-ignore-next-line
 91|    set bereq.max_reuse_idle_time = 3570s; // falco-ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^
 92|    // falco-ignore-end

🔥 [ERROR] Type mismatch: bereq.max_reuse_idle_time requires type NULL but RTIME was assigned (operator/assignment)
in file.vcl at line 91, position 35
 90|    // falco-ignore-next-line
 91|    set bereq.max_reuse_idle_time = 3570s; // falco-ignore
                                      ^
 92|    // falco-ignore-end
See reference documentation: https://developer.fastly.com/reference/vcl/operators/#assignment-operators
```

I hope you can update falco to recognize this variable, or make the ignore work, so we can avoid getting errors.

Thank you very much!

**Comment by ysugimoto** [comment]
@Bio2hazard

Thanks, we'd like to know these undocumented variables that undocumented but valid on Fastly.
I will support this variable.
