### ISSUE TITLE
[BUG] Cannot get test to work

### ISSUE THREAD

**Issue by nem75** [ysugimoto/falco#387]
### Kind of proposals

- [] Parser
- [] Linter
- [] Simulator
- [x] Testing

### Describe the problem

I have a simple custom sub routine and a test for it. The test won't pass.

### VCL code that cause the problem / reproduceable

Custom sub routine in file `subs_activate_esi.vcl`:

```
sub activate_esi_recv {
    set req.http.surrogate-capability = "ckfastly=ESI/1.0";
}
```

Test in file `subs_activate_esi.test.vcl` (same directory):

```
// @scope: recv
sub test_activate_esi_recv {
    testing.call_subroutine("activate_esi_recv");

    assert.equal(req.http.surrogate_capability, "ckfastly=ESI/1.0");
}
```

### Expected behavior

The test should pass.

### Actual behavior

```shell
❯ falco test subs_activate_esi.vcl
Running tests... Done.
 FAIL  /Users/jens/Projects/fastly/files/service_www.chefkoch.de/custom_vcls/subs_activate_esi.test.vcl
  ● [RECV] test_activate_esi_recv

    Assertion Error: Assertion error: expect=ckfastly=ESI/1.0, actual=
    Actual Value:

    4|
    5|     assert.equal(req.http.surrogate_capability, "ckfastly=ESI/1.0");
    6| }

0 passed, 1 failed, 1 total, 2 assertions
```

### Additional info

Also the `--watch` parameter does not work, neither for changes on the test file nor for the actual VCL file.

**Comment by ysugimoto** [comment]
@nem75 
It seems to be written a wrong header name between VCL and testing VCL.

- The VCL sets `surrogate-capability`  (combined with `hyphen`)
- The testing VCL asserts with `surrogate_capability` (combined with `underscore`)

You can pass the test by adjusting whichever the header name.

And the `--watch` option seems to run as well with:

```
falco test subs_activate_esi.vcl --watch
```
