### ISSUE TITLE
[BUG] Parser/Linter error `client.geo.city.utf8` is not supported

### ISSUE THREAD

**Issue by davinci26** [ysugimoto/falco#42]
Hey folks,

Awesome project, I am testing it out for our vcl :)

**Describe the problem**

 I encountered the following issue:
 
 ```
 diff --git a/examples/default01.vcl b/examples/default01.vcl
index ad98204..d3e1be4 100644
--- a/examples/default01.vcl
+++ b/examples/default01.vcl
@@ -39,7 +39,8 @@ sub vcl_deliver {
 }
 
 sub vcl_fetch {
-
+  log client.geo.city;
+  log client.geo.city.utf8;
   #Fastly fetch
   return(deliver);
 }
 ```
 
 Apply the patch above and see that  [client.geo.city.utf8](https://developer.fastly.com/reference/vcl/variables/geolocation/client-geo-city-utf8/) is not recognized by the linter and that leads to errors.
 
 I am not sure how this happens since the variable is added to `predefined.yaml`. I think that these might be the only variables that have depth 4.
 
 For completeness it works on fastly fiddle [link](https://fiddle.fastlydemo.net/fiddle/b885e2cd)

**Comment by davinci26** [comment]
Actually debugged this a bit more and I think the culprit of the error is indeed the variable depth. I think applying the following patch should fix the issue:

```
diff --git a/context/context.go b/context/context.go
index 9f1f4a2..78536d7 100644
--- a/context/context.go
+++ b/context/context.go
@@ -518,7 +518,7 @@ func splitName(name string) (string, []string) {
        var first string
        var remains []string
 
-       sep := strings.SplitN(name, ".", 3)
+       sep := strings.SplitN(name, ".", 4)
        if len(sep) == 1 {
                first = sep[0]
        } else {
```

**Comment by ysugimoto** [comment]
@davinci26 It seems to fix this issue, thanks.

I'll look into other side-effects but I'm happy when you make the PR 😄
