### ISSUE TITLE
[BUG] Parser/Linter error: Falco doesnt recognize return types for subs

### ISSUE THREAD

**Issue by davinci26** [ysugimoto/falco#56]
**Describe the problem**

https://developer.fastly.com/reference/vcl/subroutines/ can have return types however Falco doesnt allow for that and it causes a parse error.

**VCL code that cause the problem**
If applicable, put your VCL code to reproduce on our environment

```
sub returns_true BOOL {
  return (true);
}
```

**Comment by davinci26** [comment]
Any issue if a make a PR for this?

**Comment by davinci26** [comment]
lol closing as duplicate of #8, might still PR though

**Comment by ysugimoto** [comment]
@davinci26 I really happy if you could make a PR for this (and #8 ) issue!
